### ISSUE TITLE
New feature request : is_displayed() equivalent DSL might get rid of JavaScript dependency

### ISSUE THREAD

**Issue by gunajoker** [gwen-interpreter/gwen-web#101]
We have come across some cases in which if the element is displayed then some DSL should be executed else some different DSL should be executed.
In these cases, I am using javascript to check if the element is displayed or not and returning it and assigning it to a variable, and then using the if condition.

Dependency on javascript will be reduced a bit if we have an is_displayed() equivalent DSL in GWEN, 

At present, we have the following DSL
         Then element should <not> be displayed
but it just checks for the condition and fails or runs fine. it cannot be used in the situation I am mentioning.

**Comment by bjuric** [comment]
Hi, turns out we just recently added a DSL for exactly that in v3.33.0:
- See https://gweninterpreter.org/docs/dsl/reference#step-if-element-condition

Please try that and let us know how it goes.

**Comment by gunajoker** [comment]
That is exactly what we wanted. thanks a ton.
