### ISSUE TITLE
GWEN is failing on starting a new browser

### ISSUE THREAD

**Issue by sse2ebdd** [gwen-interpreter/gwen-web#102]
When we try to start new browser using latest **GWEN 3.33.6**, we are getting below error

> [141ms] Failed: The path to the driver executable The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://chromedriver.chromium.org/. The latest version can be downloaded from https://chromedriver.chromium.org/downloads

We have commented property `webdriver.chrome.driver` in gwen.properties file as we want auto download chromedriver. This used to work in **GWEN 3.31.15** where web driver manager was used. But now I can see from GWEN 3.32.0, it's using embedded web driver manager provided by Selenium.

**Comment by bjuric** [comment]
We think this issue may be related to the new embedded selenium manager. Will raise this with Selenium.

In the meantime, please delete the `.cache/selenium` folder in your home directory on your machine and try running Gwen again.

**Comment by sse2ebdd** [comment]
We tried deleting `.cache/selenium`, but still getting same issue.

**Comment by bjuric** [comment]
Can you try deleting the `.cache` folder one level up?

**Comment by sse2ebdd** [comment]
Deleted `.cache`, still same issue.

**Comment by bjuric** [comment]
Did the folder get re-created, and what is in it?

**Comment by sse2ebdd** [comment]
Folder is not created after running GWEN.

**Comment by bjuric** [comment]
Hmmm. What happens if you to create an empty `.cache` folder first?

**Comment by sse2ebdd** [comment]
It remains empty on running GWEN.

**Comment by bjuric** [comment]
Could it be that there is a permissions issue on the home directory in that environment?

**Comment by bjuric** [comment]
If you turn on verbose logging (`--verbose CLI option`) in Gwen, are any additional errors logged by Selenium?

**Comment by bjuric** [comment]
Also, can you confirm that there is no driver specified in your system PATH environment variable? If there is, please remove it.

**Comment by sse2ebdd** [comment]
1. I don't think it's permission issue as with **GWEN 3.31.15** it works as expected.
2. No additional errors present with --verbose
3. Driver is not specified in PATH variable.

**Comment by bjuric** [comment]
We have implemented above in snapshot build [gwen-web-3.33.6-1-SNAPSHOT](https://s01.oss.sonatype.org/content/repositories/snapshots/org/gweninterpreter/gwen-web/3.33.6-1-SNAPSHOT/gwen-web-3.33.6-1-SNAPSHOT.zip). Since we are unable to replicate the issue, would you mind trying the snapshot in your environment and let us know how it goes? You will need to apply the new Gwen setting `gwen.web.driver.manager=WebDriverManager`

**Comment by sse2ebdd** [comment]
I have tested this and it's **working as expected**.

FYI - While testing I observed that there is no default value set to this property, if we don't mention this setting then we get error --> `Failed: Setting not found: gwen.web.driver.manager`

**Comment by sse2ebdd** [comment]
Verified using GWEN 3.34.0, working as expected.
Closing this issue.
