### ISSUE TITLE
any method to import updated meta from gwen console

### ISSUE THREAD

**Issue by gunajoker** [gwen-interpreter/gwen-web#103]
Could you please give the option to import the updated metafile from the Gwen console itself without requiring to rerun the feature file  (command prompt) something like the one below?

gwen> @import "filelocation\filename.meta"

During the development phase, the meta file goes through the change very often, I have to rerun the feature file again. This is time-consuming especially when the feature file is too long.

**Comment by bjuric** [comment]
Great idea! We will definitely look into build that soon.

**Comment by bjuric** [comment]
@gunajoker, new `load` command  released in gwen-web [v3.36.0](https://github.com/gwen-interpreter/gwen-web/releases/tag/v3.36.0). See documentation for usage at: https://gweninterpreter.org/docs/cli/repl#meta-reloads.

Please close issue when ready.

**Comment by gunajoker** [comment]
Hi bjuric
Appologize for the dealy in response and thanks for looking into it.  I have tested the load command and am completely satisfied with it. thanks again. closing the issue
