### ISSUE TITLE
anyway to soft kill the running dsl without killing gwen?

### ISSUE THREAD

**Issue by gunajoker** [gwen-interpreter/gwen-web#104]
We have to kill the Gwen or wait for the loop to timeout when the condition is not satisfied in-order to stop the execution.

For example:
The following DSL will wait until the timeout is reached which is 5min.
And I wait until the heading is displayed using 5 second delay and 300 second timeout
 ( I am not just referring to loops but any running dsl should get stopped )

If there is a way to stop the execution of the running DSL without killing the GWEN process , it would save our time in development phase.

**Comment by bjuric** [comment]
There is no way to soft exit. Do you really need a 5 minute timeout? Seems very excessive.

One idea could be to and remove the explicit timeout in the DSL and instead override [`gwen.web.locator.wait.seconds`](https://gweninterpreter.org/docs/settings/reference#gwen-web-locator-wait-seconds) to 5 minutes only for the environment where you really need it and leave the default timeout (10 secs) in your development environment.

**Comment by gunajoker** [comment]
Noted, thanks
