### ISSUE TITLE
@Examples annotation not working if no defined Examples in Scenario Outline

### ISSUE THREAD

**Issue by Rnnzzz** [gwen-interpreter/gwen-web#105]
Gwen: v3.45.0

commented Examples when executed returns an error:
![image](https://github.com/gwen-interpreter/gwen-web/assets/52254162/462ab212-bd73-4b79-a8ab-2482796fdf89)

uncommented Examples executes as expected with multiple data source (Examples and externalised data)
![image](https://github.com/gwen-interpreter/gwen-web/assets/52254162/9a486ad9-03da-40ff-b367-fb088da3a91b)

Do I need to do something on the configuration if I just want to use an externalised data as data source?

**Comment by bjuric** [comment]
Hi, thanks for raising this. We were able to replicate it and have implemented a fix in v[3.45.1](https://github.com/gwen-interpreter/gwen-web/releases/tag/v3.45.1). Please verify and close this issue when ready.

Also note that annotations are case sensitive in Gwen, so you should use `@Try` and `@Finally` in your examples above.

**Comment by Rnnzzz** [comment]
Working as expected now. will close the issue. Thanks!
