### ISSUE TITLE
Property 'unexpectedAlertBehavior' is not working as expected in latest GWEN 3.59.0

### ISSUE THREAD

**Issue by sse2ebdd** [gwen-interpreter/gwen-web#107]
### Note -
Earlier in GWEN 3.31.15, we used to have property '**gwen.web.capability.unexpectedAlertBehaviour=accept**' in gwen.properties file. But in latest GWEN if we mention this property then GWEN gives error while starting the browser.
So we tried to run on latest GWEN without this property, as in code I can see this property is set to 'accept' value --> https://github.com/gwen-interpreter/gwen-web/blob/master/src/main/scala/gwen/web/eval/driver/DriverManager.scala#L318. But what we observed is when you run on latest GWEN it actually rejects the confirmation pop-up.

### Steps to reproduce -

1. Create feature file with below content and run it
```
Feature: JS confirmation test

Scenario: JS confirmation test
Given I navigate to "https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_confirm3"
And iframe can be located by css "#iframeResult"
And try it button can be located by xpath "//button[normalize-space()='Try it']" in iframe
And expected text can be located by css "#demo" in iframe
# Below step will open JS confirmation pop-up
When I click try it button
# Below should close confirmation pop-up by accepting it
And I move to try it button
Then expected text should be "You pressed OK!"
```
2. In latest GWEN 3.59.0 this gives error, as GWEN cancels the confirmation pop-up
3. On GWEN 3.31.15, it works as expected.

**Env -**
GWEN version - 3.59.0
Chrome driver - Latest
![js-confirmation-issue](https://github.com/gwen-interpreter/gwen-web/assets/86771461/c583d0d7-5a47-418a-afd9-d4dd33f08534)

**Comment by bjuric** [comment]
Hi,

The move to DSL will not close the native alert. To do that you need to either accept or dismiss the popup with one of the popup action DSLs  here: https://gweninterpreter.org/docs/dsl#alert-and-popup-actions

In your example, you need to replace `I move to try it button` with `I accept the alert popup` to click OK.

**Comment by sse2ebdd** [comment]
@bjuric 
The move to DSL actually closes the native alert, but it cancels it instead of accepting it, that's why we are getting text '**You canceled!**'.
Please try and execute above steps one-by-one, it should help you to understand the issue.

**Comment by bjuric** [comment]
If you try replacing as per my suggestion above, the problem should disappear entirely as I did verify that using your example.  That way to accept and close a native dialog is to use the `I accept the3 alert ppoup` dialog.
The `I move to <elem>` DSL was not built that. If it worked some time ago it may be by chance due to side effects in different web driver.

**Comment by sse2ebdd** [comment]
@bjuric 
Yes, but the point of using property '**gwen.web.capability.unexpectedAlertBehaviour=accept**' is to avoid manually confirming/rejecting alert pop-up each time, earlier we used this property and it was working for us.
And now on latest GWEN it's not behaving as expected.

In our application we get such alert pop-ups at many places, and we don't want to manually accept/reject such pop-ups each time.

**Comment by bjuric** [comment]
I see, this could be happening because the latest Gwen has the latest web driver and you're relying on the web driver setting. I'm not sure how we can deal with this outside of web driver. Given this, I would recommend you be explicit. Have you tried replacing all references to that DSL?  I suspect you've been using this `move to` step in all the places where you're getting a popup.

**Comment by sse2ebdd** [comment]
@bjuric 
https://github.com/gwen-interpreter/gwen-web/blob/master/src/main/scala/gwen/web/eval/driver/DriverManager.scala#L318
On this line. I think if you just rename the property, it should solve the issue  (vior vs viour) -->
From - setDefaultCapability("unexpectedAlertBehavior", "accept", options);
To - setDefaultCapability("unexpectedAlertBehaviour", "accept", options);

**Comment by sse2ebdd** [comment]
@bjuric 
Better to give control of this property to user from properties file as it was earlier.

**Comment by bjuric** [comment]
OK, can you try setting both variants in your Gwen settings follows:?
```
gwen.web.capability.unexpectedAlertBehaviour=accept
gwen.web.capability.unexpectedAlertBehavior= accept
```

**Comment by sse2ebdd** [comment]
If I add these properties then it gives below error on latest GWEN

![image](https://github.com/gwen-interpreter/gwen-web/assets/86771461/ba999586-083f-4134-886f-0375cc788828)

**Comment by bjuric** [comment]
OK if you get the same with just the first setting, then that would to me suggest that the chrome driver is not supporting the capability. I tried it and got the same too. I'm not sure how we can resolve this except to raise it with chrome driver. Gwen passes all capabilities you configure in your settings to webdriver using the names you specify. So this is clearly not being accepted by the chrome driver anymore in latest versions it would seem.

I did notice however that in your example, you're explicitly clicking a button the get a popup. So this popup is an expected one in that example and not an unexpected one. This point might not be relevant but I'm just calling it out here.

**Comment by sse2ebdd** [comment]
I tried to rename property in properties file from 'viour' to 'vior' on **GWEN 3.31.15**, and it gives me similar (**incorrect**) behavior as compared to latest GWEN.
I can see that we are setting this property in GWEN code, so not sure how it's working when mentioned in code but throwing error when we mention it in properties file ?


Example that I have given is the simplest one for reproducing the issue, in our case many complicated cases are there and it will be huge effort to handle such pop-ups everywhere manually.

**Comment by bjuric** [comment]
I tried setting this in the Gwen code itself and got the same error: 
```
[3s 803ms] Failed ✘
  Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
  ..
  Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, .. , unexpectedAlertBehaviour: accept}]}]
```
Therefore it's not working programatically either.

**Comment by bjuric** [comment]
Also tried on latest 4.16.1 Selenium version. Same error.

**Comment by sse2ebdd** [comment]
@bjuric 
I tried below with selenium 4.16.1, and it works as expected. I tried to keep the steps similar to GWEN.

```
import org.openqa.selenium.By;
import org.openqa.selenium.UnexpectedAlertBehaviour;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;

public class mytest {

	public static void main(String[] args) {
		ChromeOptions options = new ChromeOptions();
		options.setUnhandledPromptBehaviour(UnexpectedAlertBehaviour.ACCEPT);

		WebDriver driver = new ChromeDriver(options);
		driver.get("https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_confirm3");

		WebElement iframe = driver.findElement(By.cssSelector("#iframeResult"));
		driver.switchTo().frame(iframe);
		WebElement tryItBtn = driver.findElement(By.xpath("//button[normalize-space()='Try it']"));
		WebElement expectedText = driver.findElement(By.cssSelector("#demo"));

		tryItBtn.click();
		new Actions(driver).moveToElement(tryItBtn).perform();
		System.out.println(expectedText.getText());

		driver.switchTo().defaultContent();
		driver.close();
	}
}
```

**Comment by bjuric** [comment]
I can see in your code that the capability name has been changed.  Add this to your Gwen settings and then the same should work: (note exact spelling of Behavior):

```
gwen.web.capability.unhandledPromptBehavior = accept
```

I believe this will be solved now. Thanks

**Comment by sse2ebdd** [comment]
@bjuric 
Working as expected after adding --> gwen.web.capability.unhandledPromptBehavior=accept.

In the future, it would be beneficial to have advance notice of such changes. Perhaps, when incorporating the latest version of Selenium into GWEN, we can proactively examine and assess whether any adjustments are necessary. This way, we can include these modifications as part of the GWEN release process.

Thanks.
