### ISSUE TITLE
Gwen fails to execute when using multiple tags

### ISSUE THREAD

**Issue by mairbar** [gwen-interpreter/gwen-web#24]
Invoking the `gwen-web` command with comma-delimited multiple tags (e.g. `-t "@Tag1,@Tag2,@Tag3"`) is unable to qualify a valid test for execution. Using only one tag works fine.

**Comment by bjuric** [comment]
Problem is that Gwen is checking for the presence of all the tags instead of just one of them. Working on fix now.

**Comment by bjuric** [comment]
Delivered fix in version [1.4.1](https://github.com/gwen-interpreter/gwen-web/releases/tag/v1.4.1)
Let me know how that goes @mairbar

**Comment by mairbar** [comment]
Thanks @bjuric. It works now.
