### ISSUE TITLE
too much wait time between "until" and "while" iterartions

### ISSUE THREAD

**Issue by gtsihitas** [gwen-interpreter/gwen-web#27]
Currently there is a 9 second wait between iterations

The loop will time out after 4.5 mins I think? Which means that the max number of iterations will only ever be about 30

The workaround is to call the loop again if we know we will surpass 30 iterations...but we wont always know that number as it can be dynamic. ie. if we want to verify each row in a table irrespective of the number of rows...could be 5 rows...50 rows...or 150 rows etc

**Comment by bjuric** [comment]
The current implementation sets the delay interval between iterations to one tenth of your configured `gwen.web.wait.seconds` setting (or 1 second by default if this is not set). The timeout period, is set to 3 times the `gwen.web.wait.seconds` setting (or 30 seconds by default).

Perhaps we could introduce an overloaded DSL that allows you to be explicit in setting the delay interval.  Something like the following maybe..

`<doStep> until <condition> using <interval> <second|millisecond> repeats`

Examples:

And I `repeat this` until `that is true` using `0` second repeats
And I `repeat this` until `that is true` using `1` second repeats
And I `repeat this` until `that is true` using `200` millisecond repeats

Am open to other suggestions.

**Comment by gtsihitas** [comment]
Yep that sounds good

Let's try it

**Comment by bjuric** [comment]
Added following to snapshot build `1.6.1-3-gae8f34f-SNAPSHOT` to support all variants.  @gtsihitas, let us know how you go with these before we release.

- `<step> <until|while> <condition> using <delayPeriod> <second|millisecond> delay and <timeoutPeriod> <minute|second|millisecond> timeout`
- `<step> <until|while> <condition> using <delayPeriod> <second|millisecond> delay`
- `<step> <until|while> <condition> using <timeoutPeriod> <minute|second|millisecond> timeout`
- `<step> <until|while> <condition> using no delay and <timeoutPeriod> <minute|second|millisecond> timeout`
- `<step> <until|while> <condition> using <delayPeriod> <second|millisecond> delay and no timeout`
- `<step> <until|while> <condition> using no delay and no timeout`
- `<step> <until|while> <condition> using no delay`
- `<step> <until|while> <condition> using no timeout`

Examples:

- And I `repeat this` until `that is true` using `1` second delay
- And I `repeat this` while `that is true` using` 200` millisecond delay
- And I `repeat this` until `that is true` using `2` second delay and `3` minute timeout
- And I `repeat this` while `that is true` using no delay and no timeout

This implementation sets the default delay to one tenth of your configured `gwen.web.wait.seconds` setting (or 1 second by default if this is not set). The default timeout period will be 30 times the delay (whatever it may be). These defaults are applied in all steps that don't explicitly set a delay, or a timeout, or `no delay`, or `no timeout`.
- `no delay` means that the given step will repeat immediately without delay.
- `no timeout` means that the loop will never timeout, that is; the given step won't stop repeating until the given condition is satisfied.

**Comment by gtsihitas** [comment]
That's fantastic! Very versatile

Will try a few today

Thanks Branko

George

**Comment by bjuric** [comment]
Removed `no timeout` option in snapshot build `1.6.1-4-ge7c2df6-SNAPSHOT`.  It can potentially result in endless execution. User can override the default timeout with a higher value instead if required.

DSL is now reduced to:

- `<step> <until|while> <condition> using <delayPeriod> <second|millisecond> delay and <timeoutPeriod> <minute|second|millisecond> timeout`
- `<step> <until|while> <condition> using <delayPeriod> <second|millisecond> delay`
- `<step> <until|while> <condition> using <timeoutPeriod> <minute|second|millisecond> timeout`
- `<step> <until|while> <condition> using no delay and <timeoutPeriod> <minute|second|millisecond> timeout`
- `<step> <until|while> <condition> using no delay`

**Comment by gtsihitas** [comment]
Agreed

I'll have a play today

**Comment by gtsihitas** [comment]
Works well Branko

especially <step> <until|while> <condition> using no delay

this has markedly sped up my testing

thanks!

**Comment by bjuric** [comment]
Released in v[1.7.0](https://github.com/gwen-interpreter/gwen-web/releases/tag/v1.7.0)
