### ISSUE TITLE
using "I base64 decode <element|attribute> as <attribute>"

### ISSUE THREAD

**Issue by gtsihitas** [gwen-interpreter/gwen-web#30]
Hi Branko

I'm trying to use "I base64 decode <element|attribute> as <attribute>" but I cant quite get it to work

I've tried the following
And I base64 decode "aGVsbG8=" as decoded

Error is :  ERROR - Failed step [at line 1]: And I base64 decode "aGVsbG8=" as decoded: Unbound reference: "aGVsbG8="

What's the best way to bind "aGVsbG8=" before I use it in "I base64 decode" ?

George

**Comment by bjuric** [comment]
Hi George

The dsl step for deciding strings required a reference to an attribute containing the encoded value.

Try this..

And the encoded value is "aGVsbG8="
And I base64 decode the encoded value as decoded

Or if you already have the encoded value bound in another variable, reference that. It's seems like an unusual use case to decode a literal. Perhaps you could provide more info.

**Comment by gtsihitas** [comment]
Yep I've already tried What you suggested and it doesnt work. I'll provide more details in a couple of hours

**Comment by gtsihitas** [comment]
Actually I had done something slightly different

I tried what you wrote and it works perfectly

Thanks Branko :+1: 

George

**Comment by bjuric** [comment]
ok, closing issue
