### ISSUE TITLE
replacing " with "" in a string

### ISSUE THREAD

**Issue by gtsihitas** [gwen-interpreter/gwen-web#31]
Hi 

I'm creating a file with GWEN and I need to pass a value to the file which contains double quotes

I'm using the following 
And I execute system process "ant.bat create_dynamic_xml_file -Dtemplate.file="${my xml template file}" -Dtarget.file="${my xml file}" -Dxml.response="${decoded xml}""

the value in ${decoded xml} contains double quotes. The solution to passing the string would be to use two double quotes ie. "" and it feeds it through to the file successfully as one "

I'm reading a string 
this"is"a"string
and I need to convert it to 
this""is""a""string
before I pass it to the file

How would I use GWEN to convert
this"is"a"string to this""is""a""string ?

George

**Comment by bjuric** [comment]
Hi,

Assuming that the string containing double quotes is bound to an attribute named `string1`, you can replace all double quotes in the string with two double quotes using JavaScript as follows..

`And string2 is defined by javascript "'${string1}'.replace(/"/g, '""')"` 

Then just reference `string2` where you want to use it

**Comment by gtsihitas** [comment]
That's Branko!

I'll work on this on Monday

**Comment by gtsihitas** [comment]
Hi Branko

The find replace seems to work and I can use the new value to store into a variable

However I cannot run it twice within the same session

ie.

1st run -->
 And string1 is "RzO[sql] k1lc3"
 And string2 is defined by javascript "'${string1}'.replace(/sql/g, '')"
 And string3 is "${string2}"

gwen>And string1 is "RzO[sql] k1lc3"

INFO - Evaluating Step: And string1 is "RzO[sql] k1lc3"
INFO - [1ms] Passed Step: And string1 is "RzO[sql] k1lc3"

[Passed]

gwen>     And string2 is defined by javascript "'${string1}'.replace(/sql/g, '')"

INFO - Evaluating Step: And string2 is defined by javascript "'RzO[sql] k1lc3'.replace(/sql/g, '')"
INFO - [13ms] Passed Step: And string2 is defined by javascript "'RzO[sql] k1lc3'.replace(/sql/g, '')"

[Passed]

gwen>     And string3 is "${string2}"

INFO - Starting chrome browser session
INFO - Loading chrome extension: lib\chrome-signing-1.0.1.1_0.crx
Starting ChromeDriver 2.19.346078 (6f1f0cde889532d48ce8242342d0b84f94b114a1) on port 19815
Only local connections are allowed.
INFO - Evaluating Step: And string3 is "RzO[] k1lc3"
INFO - [2s 557ms] Passed Step: And string3 is "RzO[] k1lc3"

[Passed]

2nd run in same session -->
gwen>And string1 is "RzO[sql] k1lc3"

INFO - Evaluating Step: And string1 is "RzO[sql] k1lc3"
INFO - [2ms] Passed Step: And string1 is "RzO[sql] k1lc3"

[Passed]

gwen>     And string2 is defined by javascript "'${string1}'.replace(/sql/g, '')"

INFO - Evaluating Step: And string2 is defined by javascript "'RzO[sql] k1lc3'.replace(/sql/g, '')"
INFO - [4ms] Passed Step: And string2 is defined by javascript "'RzO[sql] k1lc3'.replace(/sql/g, '')"

[Passed]

gwen>     And string3 is "${string2}"


org.openqa.selenium.WebDriverException: chrome not reachable
  (Session info: chrome=53.0.2785.143)
  (Driver info: chromedriver=2.19.346078 (6f1f0cde889532d48ce8242342d0b84f94b114a1),platform=Windows NT 6.1 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 2.06 seconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'PEXA-LT-233', ip: '10.20.22.111', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_101'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=C:\Users\GTSIHI~1\AppData\Local\Temp\scoped_dir8524_25715}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=53.0.2785.143, platform=XP, br
owserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 423b0757a630f3712acca1e9e0a5a233

[failure]

**Comment by bjuric** [comment]
I cannot replicate this. It might be a good idea to update your chromedriver to the latest here also: https://sites.google.com/a/chromium.org/chromedriver/downloads
Extract it to your system path (windows system32 folder) or put in a directory pointed to by your `webdriver.chrome.driver` setting in `gwen.properties`. Be sure to now close the browser session that Gwen opens also.

**Comment by gtsihitas** [comment]
Ok it seems to work now

The browser will launch...I need to keep the browser open to be able to run it again without failing

All good

**Comment by bjuric** [comment]
Closing issue.
