### ISSUE TITLE
Ability to change window size (ChromeDriver)

### ISSUE THREAD

**Issue by siaynoq** [gwen-interpreter/gwen-web#36]
At the moment, Chrome(Driver) doesn't easily support window size change. I am creating a prototype for testing mobile optimised websites, so it would be really great if I can use similar approach with gwen web as it's implemented with "traditional" webdriver:

    driver.manage().window().setSize(new Dimension(375, 667));

... maybe to add a 

    When I change the window size to "valuex" "valuey"

Let me know if there are alternative resolution of this proposal. Thank you in advance!

**Comment by bjuric** [comment]
Yes, we can add support for that. How about the following?

`When I resize the window to width <w> and height <h>`

Example:
`When I resize the window to width 375 and height 667`

**Comment by siaynoq** [comment]
That sounds like a perfect solution. Thanks!

**Comment by bjuric** [comment]
I've built this capability into a snapshot build and published it here:
https://oss.sonatype.org/content/repositories/snapshots/org/gweninterpreter/gwen-web/2.1.0-SNAPSHOT/gwen-web-2.1.0-SNAPSHOT.zip

Please download it and give it a try. Let me know how it goes.

**Comment by siaynoq** [comment]
Tested with ChromeDriver and GeckoDriver, both worked perfectly.
Many thanks for the quick action!

**Comment by bjuric** [comment]
Great! I'll roll this out in the next 2.2.0 release and will also include a step for maximising the current window too.

`When I maximize the window`

**Comment by siaynoq** [comment]
Nice idea. Be careful that on Mac+ChromeDriver - manage().window().maximise() works a bit odd (because of Mac's window handling), so maybe a remark about this would be useful in the docs.

**Comment by bjuric** [comment]
Will do! Thanks for that :)

**Comment by bjuric** [comment]
Released in [v2.2.0](https://github.com/gwen-interpreter/gwen-web/releases/tag/v2.2.0). Issue can be closed.

**Comment by siaynoq** [comment]
Verified, works in 2.2.0, thanks for the quick turnaround!
