### ISSUE TITLE
No DSL to support mouser hover

### ISSUE THREAD

**Issue by anshu781126** [gwen-interpreter/gwen-web#39]
No DSL to support mouser hover

Prevents from accessing menu's which are to be opened on mouse hover.

**Comment by bjuric** [comment]
Thanks @TheReturningVoid for implementing this feature. 

@anshu781126, please try the following DSL using the snapshot build below:

`I move to <element>`

Snapshot: https://oss.sonatype.org/content/repositories/snapshots/org/gweninterpreter/gwen-web/2.11.1-1-ge4d6797-SNAPSHOT/gwen-web-2.11.1-1-ge4d6797-SNAPSHOT.zip

Let us know how it goes. Cheers

**Comment by anshu781126** [comment]
Mouse hover is working as expected.

**Comment by bjuric** [comment]
Released in gwen-web v[2.12.0](https://github.com/gwen-interpreter/gwen-web/releases/tag/v2.12.0)
