### ISSUE TITLE
No DSL support for Double Click Action

### ISSUE THREAD

**Issue by pradeep-thawani** [gwen-interpreter/gwen-web#41]
Currently there is no DSL to perform double click mouse action.

It prevents user from accessing menu's or popup dialogues which gets open on double click.

**Comment by bjuric** [comment]
Hi @pradeep-thawani, thanks for raising this.

We've implemented double click support in the snapshot build below for you to try. Please download and install it and run the following DSL:
- `I double click <element>`

Snapshot build: https://oss.sonatype.org/content/repositories/snapshots/org/gweninterpreter/gwen-web/2.11.1-7-g7d7ec4a-SNAPSHOT/gwen-web-2.11.1-7-g7d7ec4a-SNAPSHOT.zip

Let us know how it goes.
Cheers

**Comment by pradeep-thawani** [comment]
Hi @bjuric, thanks for implementing this.

It works as expected for me.

**Comment by bjuric** [comment]
Released in gwen-web v[2.12.0](https://github.com/gwen-interpreter/gwen-web/releases/tag/v2.12.0)
