### ISSUE TITLE
Support for multiline argument in StepDefinition 

### ISSUE THREAD

**Issue by Rahul9844** [gwen-interpreter/gwen-web#44]
If i have below step definition
@StepDef
Scenario: I test multiline argument "<arg1>"
And test success is "$<arg1>"

While calling if we pass single line argument it works
And I test multiline argument "singleline argument"

But if we pass multi-line string argument; gwen reports undefined step
And I test multiline argument
"""
Line1...
Line2...
"""

**Comment by bjuric** [comment]
Hi, Gherkin doesn't support multi-line names for scenarios so we cannot implement multiline stepdef names.
