### ISSUE TITLE
Junit report count is incorrect in case of scenario outline.

### ISSUE THREAD

**Issue by Rahul9844** [gwen-interpreter/gwen-web#48]
![incorrectresultcount](https://user-images.githubusercontent.com/34029569/35729731-ae351b70-0835-11e8-8ba2-b58b91796893.PNG)

**Comment by Rahul9844** [comment]
![htmlreport](https://user-images.githubusercontent.com/34029569/35729936-52ff621e-0836-11e8-99f5-076da2e7b8e6.PNG)

Html report has correct count.

**Comment by bjuric** [comment]
Thanks @Rahul9844, we'll make changes to all reports to use the "expanded" scenario counts. Since Gwen expands all outlines at evaluation time. In the case of skipped or pending outlines we'll use the cumulative examples record counts. This should provide consistent figures.

**Comment by bjuric** [comment]
@Rahul9844, we've implemented the changes to cater for scenario outlines.  The counts in both reports should now match. Please try this out using the snapshot below and let us know how it goes.
- [gwen-web-2.15.0-2-g308d08a-SNAPSHOT.zip](https://oss.sonatype.org/content/repositories/snapshots/org/gweninterpreter/gwen-web/2.15.0-2-g308d08a-SNAPSHOT/gwen-web-2.15.0-2-g308d08a-SNAPSHOT.zip)

**Comment by Rahul9844** [comment]
![gwenissue48](https://user-images.githubusercontent.com/34029569/35803197-d81e039c-0a98-11e8-9407-f9a7d23710c2.png)

Tested on gwen-web-2.15.0-2-g308d08a-SNAPSHOT.zip and works as expected. Hence closing it.
