### ISSUE TITLE
Duplicate Env log files attached to failure.

### ISSUE THREAD

**Issue by Rahul9844** [gwen-interpreter/gwen-web#50]
There are duplicate environment log files (containing objects) attached in case of failure. Both the env files are identical. One is a env-all & other corresponds to env-visible. This issue is one of the side effects of not using page scopes for the objects. But an enhancement can be made to avoid uploading duplicate files.

![duplicate env log files](https://user-images.githubusercontent.com/34029569/36594932-4067c664-18c6-11e8-8d56-a9730198294d.PNG)

**Comment by bjuric** [comment]
Solution can be to only log the visible environment. If you are not using page scopes then it will include just the global scope. If you are using page scopes, then the global and actively visible scopes will be logged). This will ensure that only one environment context file (that includes all the visible bindings in either case) is logged on failure. In this way, any bindings in scopes that are not reachable at the point of failure will be omitted.

**Comment by bjuric** [comment]
Fix available in gwen-web release [2.15.5](https://github.com/gwen-interpreter/gwen-web/releases/tag/v2.15.5)

**Comment by bjuric** [comment]
@Rahul9844, please close if you're happy with this one. Cheers.
