### ISSUE TITLE
Support for appending text to a field without hitting enter key after typing text

### ISSUE THREAD

**Issue by anshu781126** [gwen-interpreter/gwen-web#54]
DSL in gwen to append text in textfield without removing existing data and without hitting enter key at the end of typing.

Reference - https://gwen-oss.slack.com/archives/C4TA7HDCK/p1523447738000079

**Comment by bjuric** [comment]
Will look at adding the following DSL to support this soon..

- `I append "<text>" to <element>`

This will not implicitly clear the text or press enter at the end.

**Comment by bjuric** [comment]
Implemented the following DSL in [2.17.0-3-g08c6a74-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/gweninterpreter/gwen-web/2.17.0-3-g08c6a74-SNAPSHOT/gwen-web-2.17.0-3-g08c6a74-SNAPSHOT.zip) build.  Please try it out and let us know how it goes:

`I append "<value>" in <element>`
- Appends a value to the existing contents of a field (does not send Enter key afterwards).
  - `<value>` = the value to append
  - `<element>` = the web element to append the value to

`I append <attribute> in <element>`
- Appends the value bound to an attribute to the existing contents of a field (does not send Enter key afterwards).
  - `<attribute>` = the name of the attribute containing the value to append
  - `<element>` = the web element to append the value into

**Comment by anshu781126** [comment]
This is working fine. Hence, closing this.
