### ISSUE TITLE
Dropdown text match taking time

### ISSUE THREAD

**Issue by anshu781126** [gwen-interpreter/gwen-web#59]
for dropdown A we get selected attribute (selected="selected") in the dom for the value which is being selected in the dropdown.
but in dropdown B we have selected a value but no selected="selected" is displayed against it in DOM.

so when gwen tries to match selected text it takes more than 4 minutes to match the text in dropdown.. 

And A dropdown text should be "ABC"

Note: Dropdown A has 2 values and Dropdown B has 2000 values.

Can gwen be optimized for this scenario?

**Comment by bjuric** [comment]
I did a test on a select control with 2000 options and Gwen matched the 1234th option in half a second. Perhaps you could provide more context or information about your current problem and I'll try to help.

**Comment by anshu781126** [comment]
Does your select control mark against that option value in the down by adding something as selected="selected". When thats the case it is working in a jiffy but when not it takes time. Not sure then how does gwen recognize what value is selected; but it rightly passes the step.

**Comment by bjuric** [comment]
Delivered in gwen-web version [2.21.0](https://github.com/gwen-interpreter/gwen-web/releases/tag/v2.21.0). Please close if you're happy with the implementation.

**Comment by anshu781126** [comment]
This worked as expected. Marking this as closed fixed.
