### ISSUE TITLE
Gwen intermittently fails to wait for expression defined via javascript predicate

### ISSUE THREAD

**Issue by Rahul9844** [gwen-interpreter/gwen-web#61]
Intermittently gwen has failed to wait (till timeout) for expressions defined via javascript predicate.

For example :
And expression is defined by javascript
"""
(()=>{
// javascript code goes here....
return "true";
})();
"""
And expression should be "true"

It was observed once that gwen failed with below error.

![waitfailure](https://user-images.githubusercontent.com/34029569/41714523-3b0b3674-756e-11e8-9a8e-53a01abd0adb.PNG)

**Comment by bjuric** [comment]
Please try `(function(){ ..})()` synax instead.

**Comment by bjuric** [comment]
@Rahul9844 please close if suggestion above resolves your issue.
