### ISSUE TITLE
Gwen javascript expression evaluation behaves inconsistent

### ISSUE THREAD

**Issue by Rahul9844** [gwen-interpreter/gwen-web#62]
I have a step-definition inside which i have defined expression which does some assertion on ui.

For example like below

![stepdef](https://user-images.githubusercontent.com/34029569/41714964-97db5ffe-756f-11e8-9316-b28f5ca5f97e.PNG)

The above if tested postively or negatively works fine. For example if i invoke it for an attribute which exists it passes as expected and if i invoke it for an attribute which does not exists it does not passes as expected.

But in below scenario it does not work fine.
1. Invoked for an attribute which exists --> passes (expected to pass)
2. Invoked for an attribute which exists --> passes (expected to pass)
3. Invoked for an attribute which does not exists --> passes (expected to fail)

Below is attached screen shot of the same.

![gwenexpression result](https://user-images.githubusercontent.com/34029569/41714914-772e66d4-756f-11e8-89d8-7d90f1fcdaaf.PNG)

**Comment by bjuric** [comment]
Please try `(function(){ ..})()` synax instead

**Comment by bjuric** [comment]
@Rahul9844 please close if suggestion above resolves your issue.
