### ISSUE TITLE
gwen script not interpreting all command line arguments 

### ISSUE THREAD

**Issue by bitcoder** [gwen-interpreter/gwen-web#67]
I've downloaded the gwen-workspace from "https://github.com/gwen-interpreter/gwen-web/releases/tag/v2.34.1".
Whenever trying it out, I found that the "gwen" bash script does not accept "-m" argument although it announces it as available in the help.
It seems the bash script is hardcoding "-m" and not passing the command arguments to the java application.
This problem is not restricted to "-m" but may affect other parameters though.

`
./gwen --help
Target browser is chrome
Target environment is local
   _
  { \," Gwen Package Manager
 {_`/   gwen-gpm v2.0.0
   `
[gwen-gpm] update gwen-web gwen.gwen-web.version target/gwen/gwen-web -p gwen.properties,browsers/chrome.properties,env/local.properties
[gwen-gpm] Target gwen-web version is latest
[gwen-gpm] The latest available gwen-web version is 2.34.1
[gwen-gpm] You'll be using the latest gwen-web ..Very good!
[gwen-gpm] gwen-web-2.34.1 exists in download cache
[gwen-gpm] gwen-web-2.34.1 already installed in target/gwen/gwen-web
   _
  { \," Gwen Package Manager
 {_`/   gwen-gpm v2.0.0
   `
[gwen-gpm] update selenium gwen.selenium.version target/gwen/selenium -p gwen.properties,browsers/chrome.properties,env/local.properties
[gwen-gpm] selenium is provided by Gwen

Launching gwen

   __ ___      _____ _ __     _
  / _` \ \ /\ / / _ \ '_ \   { \,"
 | (_| |\ V  V /  __/ | | | {_`/
  \__, | \_/\_/ \___|_| |_|   `
  |___/

Welcome to gwen-web v2.34.1

Usage: gwen [options] [<features>]

  --version                Prints the implementation version
  --help                   Prints this usage text
  -b, --batch              Batch/server mode
  -|, --parallel           Parallel batch execution mode)
  -p, --properties <properties files>
                           Comma separated list of properties file paths
  -r, --report <report directory>
                           Evaluation report output directory
  -f, --formats <formats>  Comma separated list of report formats to produce
         - Supported formats include: html,slideshow,junit,json (default is html)
  -t, --tags <tags>        Comma separated list of @include or ~@exclude tags
  -n, --dry-run            Do not evaluate steps on engine (validate for correctness only)
  -i, --input-data <input data file>
                           Input data (CSV file with column headers)
  -m, --meta <meta files>  Comma separated list of meta files and directories
  <features>               Space separated list of feature files and/or directories

 ./gwen -m meta
Target browser is chrome
Target environment is local
   _
  { \," Gwen Package Manager
 {_`/   gwen-gpm v2.0.0
   `
[gwen-gpm] update gwen-web gwen.gwen-web.version target/gwen/gwen-web -p gwen.properties,browsers/chrome.properties,env/local.properties
[gwen-gpm] Target gwen-web version is latest
[gwen-gpm] The latest available gwen-web version is 2.34.1
[gwen-gpm] You'll be using the latest gwen-web ..Very good!
[gwen-gpm] gwen-web-2.34.1 exists in download cache
[gwen-gpm] gwen-web-2.34.1 already installed in target/gwen/gwen-web
   _
  { \," Gwen Package Manager
 {_`/   gwen-gpm v2.0.0
   `
[gwen-gpm] update selenium gwen.selenium.version target/gwen/selenium -p gwen.properties,browsers/chrome.properties,env/local.properties
[gwen-gpm] selenium is provided by Gwen

Launching gwen

   __ ___      _____ _ __     _
  / _` \ \ /\ / / _ \ '_ \   { \,"
 | (_| |\ V  V /  __/ | | | {_`/
  \__, | \_/\_/ \___|_| |_|   `
  |___/

Welcome to gwen-web v2.34.1

Error: Unknown option -m
Try --help for more information.
Failed to read in gwen arguments
`

**Comment by bjuric** [comment]
Hi, it's because the -m option is already specified in the root wrapper script of the workspace. All meta should go in the meta folder as set in that script. I'll remove it from the help in the workspace. Thanks for pointing that out.

**Comment by bjuric** [comment]
It could be better if I remove the hard coded meta default so that the user can specify different meta directories if they wish to execute different meta at times.

**Comment by bitcoder** [comment]
yep, also think so. If users are able of passing all the parameters ahead, as supported by gwen jar, better, it would be more flexible

**Comment by bjuric** [comment]
Updated workspace zip accordingly. Removed hard code values for both `-m,--meta` and `-r,--report` options so user can now specify these. Also added `-h,--help` to print wrapper script help.

**Comment by bitcoder** [comment]
great work!

**Comment by bjuric** [comment]
If you could test that in your env and close if all is OK. That would be good. You on linux or windows?

**Comment by bitcoder** [comment]
I'm on OSX Mojave :)
If I specify "-m" once it works fine; if I specify it multiple times (should it be supported? maybe not) then it gives an error.

`
$ ./gwen -m meta -m features
Target browser is chrome
Target environment is local
   _
  { \," Gwen Package Manager
 {_`/   gwen-gpm v3.0.1
   `
[gwen-gpm] update gwen-web gwen.gwen-web.version target/gwen/gwen-web -p gwen.properties,browsers/chrome.properties,env/local.properties
[gwen-gpm] Target gwen-web version is latest
[gwen-gpm] The latest available gwen-web version is 2.34.1
[gwen-gpm] You'll be using the latest gwen-web ..Very good!
[gwen-gpm] gwen-web-2.34.1 exists in download cache
[gwen-gpm] gwen-web-2.34.1 already installed in target/gwen/gwen-web
   _
  { \," Gwen Package Manager
 {_`/   gwen-gpm v3.0.1
   `
[gwen-gpm] update selenium gwen.selenium.version target/gwen/selenium -p gwen.properties,browsers/chrome.properties,env/local.properties
[gwen-gpm] selenium is provided by Gwen

Launching gwen

   __ ___      _____ _ __     _
  / _` \ \ /\ / / _ \ '_ \   { \,"
 | (_| |\ V  V /  __/ | | | {_`/
  \__, | \_/\_/ \___|_| |_|   `
  |___/

Welcome to gwen-web v2.34.1

Error: Unknown option -m
Try --help for more information.
Failed to read in gwen arguments

`

By the way,  if I try invoke gwen-web directly I also have the same behavior:

`
./target/gwen/gwen-web/bin/gwen-web  -m meta -m features

   __ ___      _____ _ __     _
  / _` \ \ /\ / / _ \ '_ \   { \,"
 | (_| |\ V  V /  __/ | | | {_`/
  \__, | \_/\_/ \___|_| |_|   `
  |___/

Welcome to gwen-web v2.34.1

Error: Unknown option -m
Try --help for more information.
Failed to read in gwen arguments
`

**Comment by bjuric** [comment]
It's not supported. You have to specify a comma separated list in one `-m` option if you want to load more than one meta.

**Comment by bitcoder** [comment]
So I'll close this as it seems to be fine in v2.34.1
