### ISSUE TITLE
DSL for file upload?

### ISSUE THREAD

**Issue by dfriquet** [gwen-interpreter/gwen-web#70]
Hi there,

Have I missed anything in the supported Web-DSL, or is there any known recipe, to interact with `<input type="file" />`?

I've searched the web for Selenium-based solutions and tricks, like [`sendKeys`](http://allselenium.info/working-with-file-upload-using-java-selenium-webdriver/), but I couldn't figure out how to translate it in Gwen-Web DSL: `I  type "file:///path/to/file.odt" in uploadInput` doesn't seem to send anything to the input, but rather to the window itself…

How do you manage to test this kind of requirements?

Best regards.

PS : trying out Gwen for a couple of days now, I find that idea of yours (meta-programming Cucumber with ready-to-use web steps) wonderful, and really efficient!

**Comment by bjuric** [comment]
@dfriquet Thank you for raising this issue. We were able to replicate it and have rolled out a fix. The `I type "file://path/to/file.odt" in uploadInput` DSL you are using should work now. Gwen should auto update the next time you run it.

**Comment by dfriquet** [comment]
@bjuric Indeed, it's now working! Thanks a lot for this really quick fix :+1: 

May I suggest an entry in the FAQ? It seems that it's only working with absolute "file-system path" like `/path/to/file`.

**Comment by bjuric** [comment]
@dfriquet I've added it to the FAQ here:
- https://github.com/gwen-interpreter/gwen-web/wiki/FAQ#how-do-i-upload-files-to-a-file-input-field

Please close this issue when ready.

Cheers.

**Comment by dfriquet** [comment]
@bjuric I'm definitely ready to close this issue :ok_hand: 

Thank you :bowing_man:
