### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by JohnSColeman** [gwen-interpreter/gwen-web#75]
Gwen-web doesn't seem to have a code coverage feature (see [cypress](https://docs.cypress.io/guides/tooling/code-coverage#Using-code-transpilation-pipeline)).

**Comment by bjuric** [comment]
We had never considered that someone might want to use Gwen for code coverage purposes.

**Comment by JohnSColeman** [comment]
> We had never considered that someone might want to use Gwen for code coverage purposes.

Understood, it's a completely separate concern but an essential part of a comprehensive test platform. I wonder if it is possible to integrate as an addition like cypress does?

**Comment by bjuric** [comment]
You can instrument your code, run Gwen tests over it, and view your coverage without requiring any special integration in Gwen. And you can use any coverage tool of your choice without being locked into whichever one a potential integration solution we introduce might be coupled to. Being a separate testing concern, our preference would be to keep it out of Gwen and allow users freedom of choice over which coverage tools they wish to use.

**Comment by bjuric** [comment]
Would be great if you could try it and let us know how it goes.

**Comment by bjuric** [comment]
@JohnSColeman have you had a chance to try above? Would be keen to know how it went.

**Comment by bjuric** [comment]
We'll take this as a comment. Closing.

**Comment by JohnSColeman** [comment]
Sorry, too busy with other work to focus on this.
