### ISSUE TITLE
"ARROW_UP" and  "ARROW_DOWN" key sending steps not working in ag-grid cell

### ISSUE THREAD

**Issue by sse2ebdd** [gwen-interpreter/gwen-web#82]
"ARROW_UP" and  "ARROW_DOWN" key sending steps not working (i.e when trying to send arrow key, the locator is losing focus, and coz of that arrow key action is not performed)

This issue is reproduced since GWEN - 2.53.0

**Env Details**
Gwen Version - 2.53.0
Chrome Driver - Latest (92)

**Comment by bjuric** [comment]
Do you have more details or a page that we can replicate this with? If not, are you able to put together a Selenium code snippet that does work on the page you are testing?

**Comment by bjuric** [comment]
Found a solution to keep focus when sending keys. Fix will be available in upcoming release 2.53.3.

**Comment by sse2ebdd** [comment]
Hi, I tried using release 2.53.3, but still facing the issue.

The element on which I am trying to perform the action is <ng-component> 

**Step in use**: I send "ARROW_UP" to  **ELEMENT** while **CONDITIONISTRUE** using 100 millisecond delay and 5 second timeout

**Comment by bjuric** [comment]
Fixed in release v2.53.4

**Comment by sse2ebdd** [comment]
Verified on Release 2.53.4 and works now. Thus, closing the ticket.
