### ISSUE TITLE
When an attribute is defined to fetch data from database then gwen fails to compare it if it is multiline

### ISSUE THREAD

**Issue by sse2ebdd** [gwen-interpreter/gwen-web#84]
Following are the steps to reproduce the bug:

Step1: Store some multiple lines of text in a column which is of blob data type in DB
For example, the text can be as follows:
```
{1:F01 0000000000} {2:I999USER5AUTXOMAU1003}
{3:{108:}}
```

Step2: Run this DSL on the GWEN console:
```
And expected_text is
"""
{1:F01 0000000000} {2:I999USER5AUTXOMAU1003}
{3:{108:}}
"""
```

Step3: Now define a attribute which will fetch the data from db like below.
`And actual_text is defined in the ${dbName} database by sql "select Utl_Raw.Cast_To_Varchar2(Dbms_Lob.substr($<column_name>,2000,1)) from $<table_name>"`

Step4: Run below DSL and observe the result.
And actual_text should be
"""
${expected_text}
"""

OBSERVATION: Step4 should be passed, but it fails even if the actual and expected values are the same. 
The error message showing the actual and expected message is exactly same.

### Note
This is a regression issue found while upgrading from 2.43.0 to 2.53.0
Gwen Version - 2.53.0
Chrome Driver - Latest (92)

**Comment by bjuric** [comment]
Are you able to provide the value of `actual_text` as it appears in the environment trace attached to the report?

**Comment by bjuric** [comment]
Can you try the following? Note the new line after the reference. They might look the same, but there must be something subtly different for this comparison to be failing.

```
And actual_text should be
"""
${expected_text}

"""
```

**Comment by sse2ebdd** [comment]
Sure i will try above.

**Comment by sse2ebdd** [comment]
Hi branko tried with newline but dint help

Below is the details from env stack 

```
processed exp msg/javascript : "'{1:F21ABCDEFG1AXXX0235005634}{2:O9991003100906DEFGXXXX4A1000008208451009061003N}{3:{108:MT999}}{4:\r\n:20:02869\r\n:21:1000661\r\n:79:NARRATIVE TEXT\r\n-}{5:{CHK:65FAC4B68205}{TNG:}}{S:{COP:P}}'"

 
 

actual message : "{1:F21ABCDEFG1AXXX0235005634}{2:O9991003100906DEFGXXXX4A1000008208451009061003N}{3:{108:MT999}}{4:
                        :20:02869
                        :21:1000661
                        :79:NARRATIVE TEXT
                        -}{5:{CHK:65FAC4B68205}{TNG:}}{S:{COP:P}}"
```

**Comment by bjuric** [comment]
The expected value has `\r\n` literals. So it' is different.

**Comment by sse2ebdd** [comment]
I verified that by using simple attributes instead of defining attribute using js predicate its woking.
Thus closing this bug as non-issue.
