### ISSUE TITLE
Extra comma after "line"

### ISSUE THREAD

**Issue by charleslcso** [gwen-interpreter/gwen-web#86]
Hello

I'm new to Gwen. Tried to use it to build some test cases. 

I used this command to run the test: gwen -b -m 1_MJ-181.meta -f json -Dgwen.web.browser.headless=true --parallel -r target/reports features

and it will generate a json file.

Upon feeding the content of this json file into json parser, it shows that there is a comma at end of all lines "line": X

I believe these comma shouldn't be there.

Or am I doing something wrong?

>     
"tags": [
      {
        "name": "@MJ-181",
        "line": 1,
      }
    ],
    "elements": [
      {
        "keyword": "Scenario",
        "id": "scenario;test-google-search-(gwen-web-demo);1",
        "line": 6,
        "name": "Test Google search (Gwen-web-demo)",
        "description": "",
        "tags": [
          {
            "name": "@MJ-182",
            "line": 5,
          },
          {
            "name": "@MJ-186",
            "line": 5,
          }
        ],
        "type": "scenario",

**Comment by bjuric** [comment]
Thanks for raising this @charleslcso. We've release a fix in gwen-web v[3.53.7](https://github.com/gwen-interpreter/gwen-web/releases/tag/v2.53.7). Please try that and close issue when ready.

**Comment by charleslcso** [comment]
Nice! It is fixed! Closing issue now.
