### ISSUE TITLE
chrome driver for Pi 4b

### ISSUE THREAD

**Issue by charleslcso** [gwen-interpreter/gwen-web#87]
Hello,

One of our testing env is the Pi 4b.

We see from Gwen output that it will look for chromedriver and download it if needed.

> 
INFO - Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
INFO - Downloading https://chromedriver.storage.googleapis.com/95.0.4638.54/chromedriver_linux64.zip
INFO - Extracting driver from compressed file chromedriver_linux64.zip
INFO - Exporting webdriver.chrome.driver as /home/ubuntu/.cache/selenium/chromedriver/linux64/95.0.4638.54/chromedriver

But this version is having issue:

>
Nov 02, 2021 3:51:32 PM org.openqa.selenium.os.OsProcess checkForError
SEVERE: org.apache.commons.exec.ExecuteException: Process exited with an error: 2 (Exit value: 2)

I downloaded the proper version for the Pi 4b, sym-linked it in the above directory, and Gwen will use the other version will no problem.

Is it possible to specify the system's chromedriver using an external file so all projects will share the same chromedriver? We are going to run tests on various platforms, and the version downloaded from googleapis.com is not 100% working.

**Comment by bjuric** [comment]
Gwen uses an embedded WebDriverManager which automatically selects driver versions for you. However it also enables you to explicitly specify which driver version you want using the `wdm.chromeDriverVersion` system property (for chromedriver). So you can set that and pass it to Gwen. See: https://bonigarcia.dev/webdrivermanager/#advanced-configuration

**Comment by bjuric** [comment]
Also you can point Gwen to a driver file. See: https://github.com/gwen-interpreter/gwen-web/wiki/Web-Driver-Management#point-gwen-to-your-installed-web-driver

**Comment by charleslcso** [comment]
Nice. Thanks again.
