### ISSUE TITLE
Tag filters should not be applied to meta files

### ISSUE THREAD

**Issue by sse2ebdd** [gwen-interpreter/gwen-web#89]
In GWEN 3, if you run gwen with tag filters, it also checks whether imported meta files satisfy that tag filters or not and imports them accordingly. --> "Feature file skipped (does not satisfy tag filters): BDD\features-meta\test.meta"
Earlier in 2.x version, GWEN used to apply tag filters only to feature file.

### Env
Gwen Version - 3.0.6
Chrome Driver - Latest (96)

**Comment by sse2ebdd** [comment]
Raised this on wrong project. Hence closing it.

**Comment by bjuric** [comment]
Thanks for raising this issue. Fixed in gwen-web v[3.0.8](https://github.com/gwen-interpreter/gwen-web/releases/tag/v3.0.8).

**Comment by sse2ebdd** [comment]
Verified this issue on GWEN v3.0.8.
It's working as expected, hence closing this issue.
