### ISSUE TITLE
GWEN fails if single line JavaScript contains if condition

### ISSUE THREAD

**Issue by sse2ebdd** [gwen-interpreter/gwen-web#90]
If you executet JS -->

`(function(){ if ("3" == "3") {return true;} else {return false;} })()`

Gwen throws error --> Failed: Unbound reference: ("3" == "3") return true;}else{return false;}})()"
![image](https://user-images.githubusercontent.com/86771461/144593492-389bb8c5-6bb4-4084-90be-7b15fb8f3667.png)

The above javascript works in 2.53.5 version.

### Env
Gwen Version - 3.0.6
Chrome Driver - Latest (96)

**Comment by bjuric** [comment]
Thanks for raising this issue. Fixed in gwen-web v[3.0.8](https://github.com/gwen-interpreter/gwen-web/releases/tag/v3.0.8).

**Comment by sse2ebdd** [comment]
Verified this issue on GWEN v3.0.8.
It's working as expected, hence closing this issue.
