### ISSUE TITLE
GWEN is failing while executing system process

### ISSUE THREAD

**Issue by sse2ebdd** [gwen-interpreter/gwen-web#97]
**Steps to reproduce -**
1. System process step is failing with error --> And I execute system process "cmd.exe /c echo Hi > test.txt"
2. This was working on GWEN 3.2.0

**Env -**
GWEN version - 3.31.4
Chrome driver - Latest

![system-process-execution-issue](https://user-images.githubusercontent.com/86771461/193042998-f939495a-e4c7-4e2c-bd3c-82ed7dd050a4.png)

**Comment by bjuric** [comment]
Issue was that windows commands were being execute like unix commands. Fixed. Will be available in next release.

**Comment by bjuric** [comment]
Fix released in gwen-web [v3.31.6](https://github.com/gwen-interpreter/gwen-web/releases/tag/v3.31.6). Please close when ready.

**Comment by sse2ebdd** [comment]
Tested on GWEN 3.31.6, working as expected.
