### ISSUE TITLE
GWEN is failing while executing system process when '\' is present in system process call

### ISSUE THREAD

**Issue by sse2ebdd** [gwen-interpreter/gwen-web#98]
**Steps to reproduce -**
```
Feature: TEST

Scenario: TEST
# Works when '\' is not present at end of directory path 
And I execute system process "cmd.exe /c E: && cd E:temp\temp-sudirectory && echo Hi > test1.txt"

# Works with '\' twice at end of directory path
And I execute system process "cmd.exe /c E: && cd E:temp\temp-sudirectory\\ && echo Hi > test2.txt"

# Fails with single '\' at end of directory path
And I execute system process "cmd.exe /c E: && cd E:temp\temp-sudirectory\ && echo Hi > test3.txt"
```

This was working on GWEN 3.2.0

Env -
GWEN version - 3.31.9
Chrome driver - Latest

![backslash-system-process-execution-issue](https://user-images.githubusercontent.com/86771461/194234790-61ec7ded-e728-4a59-8e01-a918bf646813.png)

**Comment by bjuric** [comment]
Problem was a scala library override. Fixed in [v3.31.10](https://github.com/gwen-interpreter/gwen-web/releases/tag/v3.31.10)

**Comment by sse2ebdd** [comment]
Working as expected on GWEN 3.31.10.

**Comment by sse2ebdd** [comment]
@bjuric 
This issue is again reproducible on latest GWEN 3.46.0.
Hence re-opening this issue.

**Comment by bjuric** [comment]
It appears that this is the result of the latest scala libraries being applied which now require escaping. Can I suggest that you escape all backslashes as `\\` or use a forward slash `/` instead as your path separator character.

**Comment by bjuric** [comment]
Also please try running with Java 11+ (Java 17 recommended). Note that we no longer support Java 8 since Selenium will not be supporting it after 30 Sep this year.

**Comment by sse2ebdd** [comment]
Okay thanks, will do one run after escaping backslashes and with Java 11+.
It may take some time. In case of any issues will update here, thanks.

**Comment by sse2ebdd** [comment]
Working as expected, after removing backslashes at the end of path. 
Hence closing this issue.
